version: "3.6"

services: 
  server:
    env_file: docker.dev.env
    build: backend/
    restart: always
    volumes: 
      - ./backend:/backend
    ports: 
      - "3000:3000"
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://escape@postgres/escape
  fontend:
    build: frontend/netcentric-escape-game
    restart: always
    volumes: 
      - ./netcentric-escape-game:/frontend
    ports: 
      - "4000:3000"
    depends_on: 
      - server
  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: escape
      POSTGRES_DB: escape