version: "3.6"

services: 
  api:
    env_file: docker.dev.env
    build: backend/
    restart: always
    volumes: 
      - ./backend:/backend
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://escape@postgres/escape
  frontend:
    build: frontend/netcentric-escape-game
    restart: always
    volumes: 
      - ./frontend/netcentric-escape-game:/frontend
  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: escape
      POSTGRES_DB: escape
  nginx:
    image: nginx
    ports: 
      - "3000:80"
      - "443:443"
    depends_on: 
      - api
      - frontend
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/sites-enabled/server.conf:/etc/nginx/sites-enabled/server.conf