version: '3'

services: 
  api:
    build: backend/
    restart: always
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://escape@postgres/escape
      NODE_ENV:
      AES_SECRET:
      JWT_SECRET:
  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: escape
      POSTGRES_DB: escape
  nginx:
    image: nginx
    restart: always
    depends_on: 
      - api
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
